name: v2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.4+7

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flex_color_scheme: ^8.2.0
  flutter_slider_drawer: ^2.1.3
  google_fonts: ^4.0.3
  bottom_sheet: ^4.0.4
  # flutter_riverpod: ^2.1.3
  # go_router: ^6.0.6
  # flutter_widget_from_html_core: ^0.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  pinput: ^2.2.23
  dio: ^4.0.6
  image_picker: ^0.8.6+1
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  # flutter_blue: ^0.8.0
  flutter_blue_plus: ^1.35.5
  map_launcher: ^4.0.0
  permission_handler: ^12.0.1
  # go_router_flow: ^6.0.0+3
  flutter_easyloading: ^3.0.5
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  visibility_detector: ^0.3.3
  flutter_credit_card: ^3.0.6
  convert_vietnamese: ^0.0.9
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^5.0.2
  local_auth: ^2.1.6
  get: ^4.6.5
  ultra_qr_scanner: ^2.1.0
  webview_flutter: ^4.2.4
  lottie: ^3.0.0
  device_info_plus: ^9.1.2
  intro_slider: ^4.2.1
  awesome_notifications_core: ^0.9.3 # <~ always ensure to use the latest version
  awesome_notifications: any
  flutter_localizations:
    sdk: flutter
  # one_context: ^2.1.0
  # sentry_flutter: ^7.12.0

dev_dependencies:
  # flutter pub run change_app_package_name:main jp.takaraservice.evcharge
  change_app_package_name: ^1.4.0
  # flutter pub run flutter_launcher_icons
  flutter_launcher_icons: "^0.13.1"
  build_runner: ^2.4.6
# flutter pub run flutter_native_splash:create
  flutter_native_splash: ^2.3.5

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 23 
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:

  color: "#ffffff"
  image: assets/images/logo.JPG
  color_dark: "#ffffff"
  android_12:
  fullscreen: true