import 'package:get/get.dart';

class MyTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "home": "Home",
          "history": "History",
          "notification": "Notification",
          "setting": "Setting",
          "dark_mode": "Dark mode",
          "light": "Light",
          "dark": "Dark",
          "email": "Email",
          "password": "Password",
          "confirm_password": "Confirm password",
          "dont_blank": "Don\"t leave blank",
          "more_than_6": "Field more than 6 characters and less than 32",
          "password_incorrect": "Current password incorrect!",
          "email_invalid": "Email invalid",
          "register": "Register",
          "login": "Login",
          "phone": "Phone",
          "power_socket_available": "Power socket available",
          "maps_app_not_found": "Maps app not found",
          "scan_qr": "Scan QR",
          "search": "Search",
          "filter_name_or_address":
              "Filter charge car location by name or address",
          "data_not_found": "Data not found",
          "number_kwh": "Number kwh",
          "total_amount": "Total amount",
          "charging": "Charging",
          "stop_charging": "Stop charging",
          "account": "ACCOUNT",
          "verify_account": "Verify account",
          "verified": "Verified",
          "not_verified": "Not Verified",
          "info_account": "Infomation account",
          "delete_account": "Delete account",
          "sign_out": "Sign out",
          "settings": "Settings",
          "system": "System",
          "language": "Language",
          "version": "Version",
          "app_version": "Application verion",
          "full_name": "Full name",
          "success": "Succuess",
          "fail": "Fail",
          "open_settings": "Open settings & Refresh",
          "grant_location_and_camera":
              "Grant location and camera permissions so we can better serve you",
          "delete_account_message":
              "Are you sure to permanently delete your account, your data will not be restored.",
          "yes": "Yes",
          "no": "No",
          "register_success_message":
              "Successful account creation, check email to activate the account.",
          "fail_again": "Operation failed, please try again later.",
          "login_success": "Login success",
          "account_nonactive": "Account not activated, activate to login",
          "user_pass_invalid": "Email or password is invalid",
          "full": "FULL",
          "splash_screen_message":
              "Using the NextEnergy charger is as easy as holding your smartphone over the QR code! It is a service application that can use chargers for electric vehicles \"EV/PHEV\" in general.",
          "qr_code_invalid": "Invalid QR code or charging hole is in use",
          "charge_within": "Charge within ",
          "register_on_failed":
              "We cannot confirm your authorization! To use it, please contact the facility manager displayed on the charging facility.",
          "time": "Time",
          "h": "H",
          "start": "Start",
          "cancel": "Cancel",
          "skip": "Skip",
          "server_busy": "The server is busy, please try again",
          "retry": "Retry",
          "field_format_invalid": "Field format invalid",
          "unable_to_connect":
              "Unable to connect to the system, please try again later!",
          "create_booking_success": "Create booking charging success",
          "charging_order_completed": "Charging order completed",
          "reset_password": "Reset password",
          "from": "From ",
          "to": "To ",
          "save": "Save",
          "you_have_not_complete_the_payment":
              "You have not completed the payment yet. Do you still want to exit?",
          "continue_payment": "Continue Payment",
          "machine_available": "Machine availiable",
          "open_map": "Open Map",
          "find_an_ev_charger": "Find an EV charger station",
          "found": "Found",
          "charge_station": "Charger station",
          "available": "available",
          "detail": "Detail",
          "change_password": "Change password",
          "password_current": "Password current",
          "password_new": "Password new",
          "member_code": "Member code",
          "profile": "Profile",
          "expiry_date": "Expiry date",
          "account_exists": "Account exists",
          "unregistered_account": "Unregistered account",
          "confirm": "Login",
          "forget_password": "Forget password ?",
          "already_have_an_account": "Already have an account ready",
          "request_otp": "Request OTP",
          "verification": "Verification",
          "enter_the_code_sent_to_my_phone": "Enter the code sent to my phone",
          "didnt_recieve_code": "Didn't recieve code ?",
          "resend": "Resend",
          "invalid_pin_code": "Invalid PIN code",
          "charging_can_not_go_back": "Charging can't go back",
          "connecting": "Connecting",
          "disconnect": "Disconnect",
          "touch_to_reconnect": "Touch to reconnect",
          "charge": "Charge",
          "buy_more": "Buy more",
          "pls_attaach_charger_to_vehicle":
              "Do not leave the charging stand within 2 minutes after charging starts!",
          "grant_ble":
              "Grant bluetooth permission to connect to hardware device",
          "choose_your_plant": "Choose your plant",
          "no_select_time": "No select time",
          "booking_failed_to_not_begin_connect":
              "Booking failed due to not being able to connect to the charger",
          "hours": "hours",
          "password_not_match": "Password does not match",
          "update_profile": "Update profile",
          "payment": "Payment",
          "request_permission": "Request permission",
          "buy": "BUY",
          "machine_availiable": "Machine Availiable",
          "time_is_still": "Your charging time is still",
          "are_you_sure_want_to_end":
              "Are you sure you want to end charging right now ?",
          "are_you_sure_want_to_end_member":
              "Are you sure you want to end charging right now ?",
          "time_remaining": "Time remaining",
          "machine_in_use": "Machine in use",
          "machine_under_maintenance":
              "Because the charging number limit has been exceeded, There are currently no charging stations available.\nWait for a while, and then continue charging again.",
          "account_not_exists": "Account not exist",
          "create_new_user": "Create new user",
          "login_exist_recreate":
              "Account exists, creating an account will delete all old data",
          "create_payment_success": "Create payment success",
          "do_you_have_charge_flag_your_car":
              "Do you have a charging flag on your car ?",
          "no_scan": "No",
          "s": "s",
          "do_you_save": "Do you want to save?",
          "note": "Warning !!! ",
          "warning_auto_payment":
              "If you remove the charging flag in the middle of the selected charging time, you will not be able to continue charging even if you push the flag again, and you will not be able to refund the amount you paid.",
          "warning_auto_payment_member":
              "Please note that if you disconnect the charging cable during charging, you will not be able to continue charging even if you connect the charging cable again, and the amount paid will not be refunded.",
          "amount_of_money": "Price",
          "do_note_remove_flag":
              "Warning!\nDo not remove the flag while charging!",
          "charging_cancel": "Charging order is cancel",
          "delete_noti": "Delete notification data?",
          "card_number": "Card number",
          "expired_date": "Expired date",
          "card_holder": "Card holder",
          "pls_input_a_valid_number": "Please input a vaid card number",
          "pls_input_a_valid_date": "Please input a valid date",
          "pls_input_a_valid_cvv": "Please input a valid CVV",
          "internet_no_connect":
              "The device is not connected to the internet, please check again.",
          "device_loggin_by_another": "Device logged in by another device",
          "notice": "Notice",
          "card_infomation": "Card infomation",
          "cofirm_charge": "Confirm",
          "no_internet_try_again": "No internet, try again",
          "complete_charging_end_processing":
              "Completed charging end processing",
          "complete_charging_end_processing_auto": "Charging completed",
          "payment_method": "Payment method",
          "input_pincode": "Enter pin code",
          "list_payment_note":
              "Credit card information will be stored in the device's memory, which will be lost when you delete the application or log out.",
          "unlock_to_view_card": "Unlock to view card information",
          "wrong_entry_delete":
              "Wrong entry for the {0}st time, after 3 times credit card data will be deleted",
          "authenticate_to_view_card_information":
              "Authenticate to view card information",
          "select_credit_card_information": "Select credit card information",
          "create_a_new_pin_code": "Create a new pincode",
          "pincode_will_used_to_store":
              "PINCode will be used to store credit card information. Forgetting PinCode will delete your credit information",
          "save_credit_card": "Save credit card",
          "delete": "Delete",
          "edit": "Edit",
          "card_infomation_has_been_deleted_due":
              "Card information has been deleted due to too many entries",
          "you_want_proces": "You want to handle it？",
          "no_info_credit_card": "No card information saved",
          "pls_enter_the_4_digit_code": "Please enter the 4 digit code.",
          "fail_again2":
              "Communication with the charger is not possible due to poor Bluetooth communication.",
          "can_not_create_due_to_the_overspep":
              "Can not create due to the overspep",
          "privacy_title": "NextEnergy Terms of Use",
          "privacy_agree": "I agree to all of the above terms",
          "privacy_confirm": "Confirm",
          "communication_with_the_server_unstable":
              "Communication with the server is currently unstable. Please wait for a while and try again.",
          "i_disagree": "I disagree",
          "i_agree_to_the_specified_commercial_transactions_law":
              "I agree to the Specified Commercial Transactions Law",
          "close": "Close",
          "no_internet_warning":
              "Communication with the server is currently unstable. Please wait for a while and try again.",
          "free": "Free",
          "pls_attaach_charger_to_vehicle_member":
              "If you disconnect the charging cable while charging, you will not be able to continue charging even if you connect the charging cable again.",
          "start_member": "Next",
          "buy_more_member": "Additional charging time",
          "forget_password_string": "Forgot your password",
          "create_account_string": "Register a new account",
          "session_device": "Login history",
          "active": "Active",
          "on_back_300s_message":
              "Please complete the charging start operation within 5 minutes after reading the QR code. Return to the starting screen.",
          "this_charger_is_out_of_order": "This charger is out of order."
        },
        'vi': {
          "home": "Trang chủ",
          "history": "Lịch sử sử dụng",
          "notification": "Thông báo",
          "setting": "Cài đặt",
          "dark_mode": "Chế độ tối",
          "light": "Sáng",
          "dark": "Tối",
          "email": "Địa chỉ email",
          "password": "Mật khẩu",
          "confirm_password": "Xác nhận mật khẩu",
          "dont_blank": "Vui lòng nhập thông tin.",
          "more_than_6": "Vui lòng nhập từ 6 đến 32 ký tự chữ và số.",
          "password_incorrect": "Mật khẩu hiện tại không đúng!",
          "email_invalid": "Vui lòng nhập địa chỉ email hợp lệ",
          "register": "Đăng ký mới",
          "login": "Đăng nhập",
          "phone": "Liên hệ",
          "power_socket_available": "Trạm sạc có sẵn",
          "maps_app_not_found": "Không tìm thấy ứng dụng bản đồ.",
          "scan_qr": "Quét QR",
          "search": "Tìm kiếm",
          "filter_name_or_address": "Tìm kiếm (tên trạm sạc, địa chỉ...)",
          "data_not_found": "Không tìm thấy kết quả.",
          "number_kwh": "Lượng điện tiêu thụ kwh",
          "total_amount": "Tổng số tiền",
          "charging": "Đang sạc",
          "stop_charging": "Kết thúc sạc",
          "account": "Tài khoản",
          "verify_account": "Xác thực tài khoản",
          "verified": "Đã xác thực",
          "not_verified": "Chưa xác thực",
          "info_account": "Thông tin tài khoản",
          "delete_account": "Xóa tài khoản",
          "sign_out": "Đăng xuất",
          "settings": "Cài đặt",
          "system": "Hệ thống",
          "language": "Ngôn ngữ",
          "version": "Phiên bản",
          "app_version": "Phiên bản ứng dụng",
          "full_name": "Họ và tên",
          "success": "Thành công",
          "fail": "Thất bại",
          "open_settings": "Hiển thị màn hình cài đặt",
          "grant_location_and_camera": "Bạn có cho phép NextEnergy hệ thống sạc Takara sử dụng camera và vị trí không?",
          "delete_account_message": "Bạn có muốn xóa tài khoản không? Tất cả dữ liệu của ứng dụng này (bao gồm cài đặt, tài khoản, cơ sở dữ liệu) sẽ bị xóa hoàn toàn.",
          "yes": "Có",
          "no": "Hủy",
          "register_success_message": "Chúng tôi đã gửi email xác thực đến địa chỉ email đã đăng ký. Vui lòng nhấp vào URL trong email trong vòng 20 phút để xác thực địa chỉ email của bạn.",
          "fail_again": "Không thể hoàn thành thao tác được yêu cầu.",
          "login_success": "Đăng nhập thành công.",
          "account_nonactive": "Tài khoản của bạn chưa được xác thực.",
          "user_pass_invalid": "Địa chỉ email bạn nhập không được đăng ký. Vui lòng kiểm tra và nhập lại.",
          "full": "Đầy",
          "splash_screen_message": "Sử dụng trạm sạc NextEnergy chỉ cần quét mã QR bằng smartphone thật đơn giản! Đây là ứng dụng dịch vụ có thể sử dụng trạm sạc cho tất cả xe điện \"EV/PHEV\" nói chung",
          "qr_code_invalid": "Mã QR không hợp lệ hoặc trạm sạc đang được sử dụng.",
          "register_on_failed": "Không thể xác nhận quyền sử dụng của khách hàng! Để sử dụng, vui lòng liên hệ với thông tin liên lạc quản lý cơ sở được hiển thị trên thiết bị trạm sạc",
          "time": "Thời gian",
          "h": "giờ",
          "start": "Đến thanh toán",
          "start_member": "Tiếp theo",
          "cancel": "Hủy",
          "skip": "Bỏ qua",
          "server_busy": "Thời gian phản hồi từ máy chủ hệ thống sạc NextEnergy Takara quá dài. Vui lòng thử lại sau.",
          "retry": "Thử lại",
          "field_format_invalid": "Có lỗi trong nội dung nhập. Vui lòng kiểm tra và nhập lại.",
          "unable_to_connect": "Không thể kết nối với hệ thống sạc NextEnergy Takara. Vui lòng thử lại sau.",
          "create_booking_success": "Đã bắt đầu sạc!",
          "charging_order_completed": "Sạc hoàn tất!",
          "reset_password": "Vui lòng nhập số điện thoại",
          "from": "từ",
          "to": "đến",
          "save": "Lưu",
          "you_have_not_complete_the_payment": "Đặt chỗ của bạn chưa được xác nhận. Bạn có muốn kết thúc không?",
          "continue_payment": "Đến thủ tục thanh toán",
          "machine_available": "Trạm sạc có sẵn",
          "open_map": "Mở bản đồ",
          "find_an_ev_charger": "Tìm trạm sạc EV",
          "found": "Tìm kiếm",
          "charge_station": "Trạm sạc",
          "available": "Có sẵn",
          "detail": "Chi tiết",
          "change_password": "Thay đổi mật khẩu",
          "password_current": "Mật khẩu hiện tại",
          "password_new": "Mật khẩu mới",
          "member_code": "Mã thành viên",
          "profile": "Cài đặt",
          "expiry_date": "Ngày hết hạn",
          "account_exists": "Tài khoản đã tồn tại.",
          "unregistered_account": "Tài khoản chưa đăng ký",
          "confirm": "Đăng nhập",
          "forget_password": "Bạn quên mật khẩu?",
          "already_have_an_account": "Tài khoản đã được đăng ký.",
          "request_otp": "Gửi SMS",
          "verification": "Xác thực",
          "enter_the_code_sent_to_my_phone": "Vui lòng nhập mã xác thực nhận được qua SMS. (Có thể mất tối đa 2 phút để nhận được)",
          "didnt_recieve_code": "Nếu không nhận được SMS",
          "resend": "Gửi lại SMS",
          "invalid_pin_code": "Số không đúng",
          "charging_can_not_go_back": "Không thể quay lại trong khi đang sạc.",
          "connecting": "Đang kết nối",
          "disconnect": "Ngắt kết nối",
          "touch_to_reconnect": "Chạm để kết nối lại",
          "charge": "Sạc",
          "buy_more": "Mua thêm",
          "buy_more_member": "Thêm thời gian sạc",
          "pls_attaach_charger_to_vehicle": "Sau khi hoàn thành giao tiếp thông tin thanh toán, cho đến khi đèn sạc phía xe sáng, vui lòng giữ Bluetooth bật và không rời khỏi đây.",
          "pls_attaach_charger_to_vehicle_member": "Cho đến khi đèn sạc phía xe sáng, vui lòng giữ Bluetooth bật và không rời khỏi đây.",
          "grant_ble": "Để kết nối với trạm sạc, vui lòng bật Bluetooth.",
          "choose_your_plant": "Chọn thời gian sạc",
          "no_select_time": "Không chỉ định thời gian",
          "booking_failed_to_not_begin_connect": "Quá trình bắt đầu sạc chưa hoàn thành. Vui lòng thao tác từ đầu.",
          "hours": "giờ",
          "password_not_match": "Mật khẩu không khớp",
          "update_profile": "Đăng ký hồ sơ",
          "payment": "Thanh toán",
          "request_permission": "Yêu cầu quyền",
          "buy": "Mua",
          "machine_availiable": "Trạm sạc có sẵn",
          "time_is_still": "Thời gian còn lại",
          "are_you_sure_want_to_end": "Thời gian sạc còn lại nhưng bạn có muốn kết thúc sạc ngay bây giờ không?\nLưu ý rằng nếu thực hiện, không thể hoàn tiền.",
          "are_you_sure_want_to_end_member": "Thời gian sạc còn lại nhưng bạn có muốn kết thúc sạc ngay bây giờ không?",
          "time_remaining": "Thời gian còn lại",
          "machine_in_use": "Máy đang sử dụng",
          "machine_under_maintenance": "Hiện tại không thể sử dụng do vượt quá số lượng có thể sạc đồng thời.",
          "account_not_exists": "Tài khoản không tồn tại",
          "create_new_user": "Tạo tài khoản mới",
          "login_exist_recreate": "Số điện thoại bạn nhập đã được đăng ký tài khoản. Nếu tạo tài khoản mới, tất cả thông tin tài khoản hiện tại sẽ bị xóa.",
          "create_payment_success": "Thanh toán thành công",
          "do_you_have_charge_flag_your_car": "Cáp sạc đã được kết nối chưa?",
          "no_scan": "Không",
          "s": "s",
          "do_you_save": "Bạn có muốn lưu không?",
          "note": "Vui lòng lưu ý",
          "warning_auto_payment": "Lưu ý rằng nếu rút cáp sạc trong khi đang sạc, việc sạc tiếp tục sẽ không thể thực hiện được ngay cả khi kết nối lại cáp sạc, và số tiền đã thanh toán cũng không thể hoàn lại.",
          "warning_auto_payment_member": "Lưu ý rằng nếu rút cáp sạc trong khi đang sạc, việc sạc tiếp tục sẽ không thể thực hiện được ngay cả khi kết nối lại cáp sạc.",
          "amount_of_money": "Số tiền",
          "do_note_remove_flag": "Vui lòng lưu ý\nTrong khi đang sạc, vui lòng không rút cáp sạc.",
          "charging_cancel": "Đơn hàng tính phí đã bị hủy",
          "delete_noti": "Bạn có muốn xóa dữ liệu thông báo không?",
          "card_number": "Số thẻ",
          "expired_date": "Ngày hết hạn",
          "card_holder": "Tên chủ thẻ (chữ cái tiếng Anh không dấu)",
          "pls_input_a_valid_number": "Vui lòng nhập số thẻ hợp lệ",
          "pls_input_a_valid_date": "Vui lòng nhập ngày hợp lệ",
          "pls_input_a_valid_cvv": "Vui lòng nhập CVV hợp lệ",
          "internet_no_connect": "Thiết bị không được kết nối với internet. Vui lòng thao tác từ đầu khi có thể sử dụng internet.",
          "device_loggin_by_another": "Thiết bị đã được đăng nhập bởi thiết bị khác",
          "notice": "Thông báo",
          "card_infomation": "Nhập thông tin thẻ",
          "cofirm_charge": "Xác nhận",
          "no_internet_try_again": "Không có internet. Thử lại",
          "complete_charging_end_processing": "Đã hoàn thành quá trình dừng sạc.",
          "complete_charging_end_processing_auto": "Sạc hoàn thành.",
          "payment_method": "Thông tin thẻ",
          "input_pincode": "Nhập mã PIN",
          "list_payment_note": "Thông tin thẻ tín dụng được lưu trong bộ nhớ thiết bị, nhưng sẽ bị mất khi xóa ứng dụng hoặc đăng xuất.",
          "unlock_to_view_card": "Mở khóa để hiển thị thông tin thẻ",
          "wrong_entry_delete": "Thông tin thẻ tín dụng sẽ bị xóa nếu nhập sai 3 lần. (Số lần sai: {0})",
          "authenticate_to_view_card_information": "Xác thực để hiển thị thông tin thẻ",
          "select_credit_card_information": "Sử dụng thông tin thẻ tín dụng đã lưu",
          "create_a_new_pin_code": "Tạo mã PIN mới",
          "pincode_will_used_to_store": "Mã PIN sẽ được sử dụng để lưu thông tin thẻ tín dụng. Nếu quên mã PIN, thông tin tín dụng sẽ bị xóa",
          "save_credit_card": "Lưu thẻ tín dụng",
          "delete": "Xóa",
          "edit": "Chỉnh sửa",
          "card_infomation_has_been_deleted_due": "Thông tin thẻ đã bị xóa do nhập quá nhiều lần sai",
          "you_want_proces": "Bạn có muốn xử lý không?",
          "no_info_credit_card": "Không có thông tin thẻ đã lưu.",
          "pls_enter_the_4_digit_code": "Vui lòng nhập mã 4 chữ số.",
          "fail_again2": "Không thể giao tiếp với trạm sạc do lỗi giao tiếp Bluetooth.",
          "can_not_create_due_to_the_overspep": "Không thể tạo quá mức",
          "privacy_title": "Hệ thống sạc NextEnergy Takara",
          "privacy_agree": "Tôi đồng ý với tất cả các điều kiện trên",
          "privacy_confirm": "Xác nhận",
          "communication_with_the_server_unstable": "Hiện tại, giao tiếp với máy chủ đang không ổn định. Vui lòng đợi một lúc và thử lại.",
          "i_disagree": "Tôi không đồng ý",
          "i_agree_to_the_specified_commercial_transactions_law": "Tôi đồng ý với Luật Giao dịch Thương mại Cụ thể",
          "close": "Đóng",
          "no_internet_warning": "Hiện tại, giao tiếp với máy chủ đang không ổn định. Vui lòng đợi một lúc và thử lại.",
          "free": "Miễn phí",
          "forget_password_string": "Vui lòng nhập số điện thoại",
          "create_account_string": "Đăng ký tài khoản mới",
          "session_device": "Lịch sử đăng nhập",
          "active": "Hoạt động",
          "on_back_300s_message": "Vui lòng hoàn thành thao tác bắt đầu sạc trong vòng 5 phút sau khi đọc mã QR. Trở về màn hình ban đầu.",
          "this_charger_is_out_of_order": "Trạm sạc này đang hỏng."
        }
      };
}
